services:
  - type: web
    name: redmart-backend
    env: node
    plan: free
    buildCommand: npm install --production || true
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: APP_NAME
        value: REDMART Enterprise API
